# ---------------------------------------------------------------------------
# sdc_scale.tcl - write a copy of the design SDC at a new clock period.
#
#   create_clock ...        : -period set to the new value, -waveform {0 P/2}
#   set_input/output_delay  : max (or unqualified) delays scaled by P/P0,
#                             so I/O budgets stay the same fraction of the cycle
#   -min delays, uncertainty, transition, loads : left unchanged
#
# Used by synth_sweep.tcl and pnr_full.tcl. Can also be run on its own to
# preview the result:
#   tclsh scripts/sweep/sdc_scale.tcl constraints/accel_top.sdc 2.5 /tmp/p2.5.sdc
# ---------------------------------------------------------------------------

proc sdc_base_period {lines} {
  foreach l $lines {
    if {[regexp {^\s*create_clock\M} $l] && [regexp -- {-period\s+([0-9]*\.?[0-9]+)} $l -> p]} {
      return $p
    }
  }
  error "sdc_scale: no create_clock -period found"
}

proc sdc_scale {in out P} {
  set fh [open $in r]; set lines [split [read $fh] "\n"]; close $fh
  set P0 [sdc_base_period $lines]
  set k  [expr {double($P) / $P0}]
  set res {}
  set nclk 0; set nio 0
  foreach l $lines {
    if {[regexp {^\s*create_clock\M} $l]} {
      regsub -- {-period\s+[0-9]*\.?[0-9]+} $l "-period $P" l
      regsub -- {-waveform\s+\{[^\}]*\}} $l "-waveform {0 [format %.4g [expr {$P / 2.0}]]}" l
      incr nclk
    } elseif {[regexp {^\s*set_(input|output)_delay\M} $l] && [regexp -- {\s-min\M} $l] == 0} {
      # first free-standing number on the line is the delay value
      if {[regexp -indices {(?:^|\s)(-?[0-9]*\.?[0-9]+)(?=\s|$)} $l -> idx]} {
        set v [string range $l {*}$idx]
        set nv [format %.4g [expr {$v * $k}]]
        set l "[string range $l 0 [expr {[lindex $idx 0] - 1}]]$nv[string range $l [expr {[lindex $idx 1] + 1}] end]"
        incr nio
      }
    }
    lappend res $l
  }
  set fh [open $out w]
  puts $fh "# Generated by sdc_scale.tcl from $in : period $P0 -> $P ns (I/O max delays x[format %.4g $k])"
  puts $fh [join $res "\n"]
  close $fh
  puts "sdc_scale: $in -> $out  (period $P0 -> $P, $nclk clock line(s), $nio I/O delay line(s) scaled)"
  return $P0
}

# Stand-alone use: tclsh sdc_scale.tcl in.sdc period out.sdc
if {[info exists argv0] && [file tail $argv0] eq "sdc_scale.tcl" && [llength $argv] == 3} {
  lassign $argv in P out
  sdc_scale $in $out $P
}
